name: Unreal Engine Windows Build

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  build_ue_project_windows:
    # Use your custom label to target your self-hosted Windows runner.
    # Example: 'self-hosted,windows' or 'self-hosted,my-windows-runner'
    runs-on: self-hosted,windows 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        lfs: true # Ensure Git LFS files are pulled

    - name: Set up Unreal Engine Environment Variables (Windows)
      # This step is crucial to ensure RunUAT.bat can be found.
      # Adjust the path to your Unreal Engine installation on the Windows runner.
      # IMPORTANT: Use forward slashes here, or double backslashes if you insist on backslashes.
      # Example: C:/Program Files/Epic Games/UE_5.3
      run: |
        echo "Adding Unreal Engine Build Tools to PATH..."
        # Replace C:/Program Files/Epic Games/UE_5.3 with your actual engine path
        set "UE_ENGINE_ROOT=C:/Program Files/Epic Games/UE_5.4" 
        set "PATH=%UE_ENGINE_ROOT%/Engine/Build/BatchFiles;%PATH%"
        echo "PATH is now: %PATH%"
      shell: cmd # Use cmd shell for Windows commands

    - name: Debug - Verify Paths and RunUAT Location
      run: |
        echo "Current Working Directory: %CD%"
        echo "GITHUB_WORKSPACE: %GITHUB_WORKSPACE%"
        echo "UE_ENGINE_ROOT: %UE_ENGINE_ROOT%"
        where RunUAT.bat || echo "RunUAT.bat not found in PATH. Check UE_ENGINE_ROOT and PATH setup."
        dir "%GITHUB_WORKSPACE%\<YOUR_PROJECT_NAME>.uproject" || echo "Project file not found at expected path."
      shell: cmd

    - name: Clean Intermediate and DerivedDataCache (Optional, but Recommended for clean builds)
      run: |
        echo "Cleaning Intermediate and DerivedDataCache directories..."
        # Use PowerShell for robust file deletion. -ErrorAction SilentlyContinue prevents errors if dir doesn't exist.
        Remove-Item -Recurse -Force ".\Intermediate" -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force ".\DerivedDataCache" -ErrorAction SilentlyContinue
      shell: powershell # Using PowerShell for robust file deletion

    - name: Run Unreal Engine Build
      run: |
        echo "Starting Unreal Engine build..."
        
        # Define project and output paths using forward slashes for RunUAT
        # GITHUB_WORKSPACE already uses backslashes on Windows, convert them.
        set "PROJECT_PATH_UNREAL=%GITHUB_WORKSPACE:\=/%/Cesium.uproject"
        set "ARCHIVE_DIR_UNREAL=%GITHUB_WORKSPACE:\=/%/BuildOutput"

        echo "Building project: %PROJECT_PATH_UNREAL%"
        echo "Archiving to: %ARCHIVE_DIR_UNREAL%"

        # Use 'call' to ensure RunUAT.bat executes correctly and returns control
        # Pass arguments directly, RunUAT is generally good at handling quoted paths
        call RunUAT BuildCookRun ^
          -project="%PROJECT_PATH_UNREAL%" ^
          -noCompileEditor ^
          -noP4 ^
          -clientconfig=Development ^
          -serverconfig=Development ^
          -nocompile ^
          -nocompileuat ^
          -nopackage ^
          -noloaddlc ^
          -pak ^
          -prereqs ^
          -nodebuginfo ^
          -targetplatform=Win64 ^
          -build ^
          -cook ^
          -stage ^
          -archive ^
          -archivedirectory="%ARCHIVE_DIR_UNREAL%" ^
          -package ^
          -compressed ^
          -distribution
      shell: cmd # Use cmd shell for RunUAT execution

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UnrealBuild-Windows
        # Path to your packaged build, ensure it's Windows-friendly
        path: ${{ github.workspace }}\BuildOutput\ 
        retention-days: 7 # How long to keep the artifact
