name: Unreal Engine Windows Build

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  build_ue_project_windows:
    # Use your custom label to target your self-hosted Windows runner.
    # Common labels might be 'self-hosted,windows' or 'self-hosted,windows-latest'.
    # Ensure your runner is configured with the labels you specify here.
    runs-on: self-hosted # Example: assuming you labeled your Windows runner with 'windows'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        lfs: true # Ensure Git LFS files are pulled

    - name: Set up Unreal Engine Environment Variables (Windows Example)
      # This step is crucial to ensure RunUAT.bat can be found.
      # Adjust the path to your Unreal Engine installation on the Windows runner.
      # Use double backslashes for paths in YAML strings, or single forward slashes.
      # For example: 'C:\\Program Files\\Epic Games\\UE_5.3\\Engine\\Build\\BatchFiles'
      run: |
        echo "Adding Unreal Engine Build Tools to PATH..."
        set "UE_ENGINE_ROOT=C:\Program Files\Epic Games\UE_5.4" 
        set "myPATH=%UE_ENGINE_ROOT%\Engine\Build\BatchFiles;%myPATH%"
        echo "myPATH is now: %myPATH%"
      shell: cmd # Use cmd shell for Windows commands

    - name: Clean Intermediate and DerivedDataCache (Optional, but Recommended for clean builds)
      run: |
        echo "Cleaning Intermediate and DerivedDataCache directories..."
        Remove-Item -Recurse -Force ".\Intermediate" -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force ".\DerivedDataCache" -ErrorAction SilentlyContinue
      shell: powershell # Using PowerShell for robust file deletion

    - name: Run Unreal Engine Build
      # Adjust PROJECT_NAME, PLATFORM, CONFIGURATION, and OUTPUT_DIR
      # For example: PROJECT_NAME=MyGame, PLATFORM=Win64, CONFIGURATION=Development
      # Check RunUAT.bat help for all options: RunUAT BuildCookRun -help
      run: |
        echo "Starting Unreal Engine build..."
        
        set "PROJECT_PATH_UNREAL=%GITHUB_WORKSPACE:\=/%/Cesium.uproject"
        set "ARCHIVE_DIR_UNREAL=%GITHUB_WORKSPACE:\=/%/BuildOutput"

        echo "Building project: %PROJECT_PATH_UNREAL%"
        echo "Archiving to: %ARCHIVE_DIR_UNREAL%"

        'C:\Program Files\Epic Games\UE_5.4\Engine\Build\BatchFiles\RunUAT.sh' BuildCookRun  -project="C:\Users\sam\Code\actions-runner\_work\cuddly-happiness\cuddly-happiness\Cesium.uproject"
          -noCompileEditor ^
          -noP4 ^
          -clientconfig=Development ^
          -serverconfig=Development ^
          -nocompile ^
          -nocompileuat ^
          -nopackage ^
          -noloaddlc ^
          -pak ^
          -prereqs ^
          -nodebuginfo ^
          -targetplatform=Win64 ^
          -build ^
          -cook ^
          -stage ^
          -archive ^
          -archivedirectory="%GITHUB_WORKSPACE%\BuildOutput" ^
          -package ^
          -compressed ^
          -distribution
      shell: cmd # Use cmd shell for RunUAT execution

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UnrealBuild-Windows
        # Path to your packaged build, ensure it's Windows-friendly
        path: ${{ github.workspace }}\BuildOutput\ 
        retention-days: 7 # How long to keep the artifact
